# start by pulling the python image
FROM python:3.9

# copy the requirements file into the image
# COPY ./requirements.txt /app/requirements.txt

# switch working directory
WORKDIR /backend/app

# install the dependencies and packages in the requirements file
RUN pip install -r /backend/app/requirements.txt

# copy every content from the local file to the image
COPY . /app

# configure the container to run in an executed manner
ENTRYPOINT [ "python" ]

CMD ["view.py" ]